# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmojiCommit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftSoup', '~> 2.3.2'
  pod 'SwiftLint', '~> 0.43.1'



  # Pods for EmojiCommit

  target 'EmojiCommitTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'EmojiCommitUITests' do
    # Pods for testing
  end

  target 'EmojiCommitWidgetExtension' do
    pod 'SwiftSoup', '~> 2.3.2'

  end

end
